In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    precision_score,
    recall_score,
    f1_score
)

df = pd.read_csv("preprocessed_data.csv")

print("Dataset Loaded Successfully!")
print("Total Vehicles:", len(df))

def range_category(range_km):

    if range_km < 150:
        return "Low"

    elif range_km < 300:
        return "Medium"

    else:
        return "High"


df["range_category"] = df["estimated_range_km"].apply(range_category)

X = df[
    [
        "battery_capacity_kwh",
        "state_of_charge",
        "battery_health",
        "energy_consumption_kwh_per_100km",
        "vehicle_age",
        "average_speed",
        "vehicle_weight_kg"
    ]
]

y = df["range_category"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(X_train, y_train)

print("\nLogistic Regression Model Trained Successfully!")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(
    y_test,
    y_pred,
    average="weighted"
)

recall = recall_score(
    y_test,
    y_pred,
    average="weighted"
)

f1 = f1_score(
    y_test,
    y_pred,
    average="weighted"
)

cm = confusion_matrix(y_test, y_pred)

print("\n======================================")
print("       LOGISTIC REGRESSION")
print("======================================")

print(f"\nAccuracy: {accuracy:.4f}")
print(f"Accuracy Percentage: {accuracy * 100:.2f}%")

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")

print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

result = pd.DataFrame({
    "Actual Range Category": y_test.values,
    "Predicted Range Category": y_pred
})

print("\nActual vs Predicted")
print("--------------------------------")
print(result.head(20))

Dataset Loaded Successfully!
Total Vehicles: 30000

Logistic Regression Model Trained Successfully!

       LOGISTIC REGRESSION

Accuracy: 0.9373
Accuracy Percentage: 93.73%
Precision: 0.9366
Recall: 0.9373
F1 Score: 0.9350

Confusion Matrix:
[[  15    0   39]
 [   0 4796  125]
 [   0  212  813]]

Classification Report:
              precision    recall  f1-score   support

        High       1.00      0.28      0.43        54
         Low       0.96      0.97      0.97      4921
      Medium       0.83      0.79      0.81      1025

    accuracy                           0.94      6000
   macro avg       0.93      0.68      0.74      6000
weighted avg       0.94      0.94      0.93      6000


Actual vs Predicted
--------------------------------
   Actual Range Category Predicted Range Category
0                    Low                      Low
1                    Low                      Low
2                    Low                      Low
3                    Low                   